project:
  type: book

book:
  title: "Agent-based modeling for sustainability"
  author: "Matt Turner"
  date: "3/14/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - programming-intro.qmd
    - part: social-science.qmd
      chapters:
      - diffusion.qmd
      - cooperation.qmd
      - coordination.qmd
      - polarization.qmd
      - uncertainty.qmd
      - rl-agents.qmd
    - part: manual.qmd
      chapters:
      - abm.qmd
      - writing.qmd
      - hpc.qmd
    - references.qmd
  

bibliography: /Users/mt/workspace/Writing/library.bib

format:
  html:
    toc: true
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
      dark:
        - darkly 
        - theme-dark.scss
    fontsize: 0.9em
    linestretch: 1.2
  pdf:
    documentclass: scrreprt



