project:
  type: book

book:
  title: "Agent-based modeling for sustainability"
  author: "Matt Turner"
  date: "4/13/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - technical-intro.qmd
    - part: diffusion.qmd
      chapters:
      - diffusion-intro.qmd
      - cooperation.qmd
      - coordination.qmd
    - part: beyond-diffusion.qmd
      chapters:
      - polarization.qmd
      - uncertainty.qmd
      - rl-agents.qmd
    - part: manual.qmd
      chapters:
      - writing.qmd
      - abm.qmd
      -  hpc.qmd
    - references.qmd
  

bibliography: 
  - /Users/mt/workspace/Writing/library.bib
  - references.bib

format:
  html:
    toc: true
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
      dark:
        - darkly 
        - theme-dark.scss
    fontsize: 0.9em
    linestretch: 1.2
  pdf:
    documentclass: scrreprt



