- Culture truly evolves when people preferentially select teachers who seem
  more successful than alternatives or are better socially connected, 
  or when people preferentially adopt behaviors that seem to
  be practiced more widely than others, or any similar social learning strategy.
  Being able to flexibly probe, sample, and integrate different sources of social and
  asocial information is a fundamental part of what it means to be human
  [@Witt2024]. Over time, stable cultural practices become established as
  various social learning strategies exercised flexibly by individuals weed out 
  less desirable Behavioral norms serve as heuristics for
  individual decision-making contingencies, such as how much to share 
  of a publicly-visible and shareable gift, or gendered division of labor from
  the relatively harmless decision of which gender leads in a social partner
  dance to who is responsible for more household chores and has freer access to
  liquid household resources or credit [@OConnor2019]. 
  We know because different cultures have different norms encoding different
  motivations for behavior in economic decisions and reasoning in general,
  self-concept, and reasoning in general, that systematically affect behavior in
  similar ways within, but not between, cultures in general [@Henrich2010].
- Of the many foundations of humanity is the unrivaled capacity to learn from
  others, with adaptations that help us decide from whom to learn, such as
  preferentially from the most apparently fit social network neighbors, or what
  features of a behavior are most desirable, such as a high prevalence of
  behavioral adoption. 
- Because of the non-linear nature of either form of adaptive social learning,
  attaining *closed-form* solutions to the formal equations is much more
  difficult and therefore more the domain of matematical biology than
  computational social science. Still, the basic predictions with some key
  simplifying, asymptotic assumptions are accessible to understand, with the
  derivations comprehensible in broad strokes.
- Because formal methods become increasingly restrictive as social behavior
  complexity is increased, simulation becomes more important. At this stage,
  simulation becomes much more accessible to many more social scientists. This
  becomes even more true as we go beyond the well-mixed assumption necessary for
  formal calculations in unconstrained or constrained contagion, and into 
  developing computational models of behavior diffusion where interaction
  structure is represented by a social network.
- NEXT: formalize success- and frequency-biased learning

#### Success-biased social learning

#### Frequency-biased social learning

